/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controllers.PendudukController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Penduduk;
import models.OperasiCRUD;
/**
 *
 * @author fikry
 */
public class DataPendudukForm extends javax.swing.JInternalFrame implements Observer {
     private PendudukController pController = new PendudukController();
     DefaultTableModel tabelModel;
    /**
     * Creates new form DataPendudukForm
     */
    public DataPendudukForm() {
        initComponents();
        pController.addObserver(this);
        resetForm();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTabelPenduduk(pController.getAllPenduduk());
        
    }
    
    private void setTabelPenduduk(List<Penduduk> lsPenduduk){
        if(lsPenduduk == null){
            JOptionPane.showMessageDialog(this, "Penduduk tidak bisa diload",
                    "Gagal Koneksi", JOptionPane.ERROR_MESSAGE);
        }else{
            tabelModel = new DefaultTableModel();
            tabelModel.setColumnIdentifiers (new String[]{
                "Id", "NIK","Nama","Jenis Kelamin","Tempat Lahir","Tanggal Lahir","Agama","Pendidikan","Jenis Pekerjaan","Alamat","Jenis Penduduuk"
            });
            for(Penduduk p : lsPenduduk){
                Object[] o = new Object[11];
                o[0] = p.getid();
                o[1] = p.getnik();
                o[2] = p.getnamapen();
                o[3] = p.getjenis_kelamin();
                o[4] = p.gettempat_lahir();
                o[5] = p.gettanggal_lahir();
                o[6] = p.getagama();
                o[7] = p.getpendidikan();
                o[8] = p.getjenis_pekerjaan();
                o[9] = p.getalamat();
                o[10] = p.getjenis_penduduk();
                tabelModel.addRow(o);
            }
            tblPenduduk.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
            tblPenduduk.setModel(tabelModel);
        }
    }
    
    private void resetForm(){
        txtnik.setText(null);
        txtnamapen.setText(null);
        txtjenis_kelamin.setText(null);
        txttempat_lahir.setText(null);
        txtagama.setText(null);
        txtpendidikan.setText(null);
        txtjenis_pekerjaan.setText(null);
        dateChooser.setCalendar(null);
        txtalamat.setText(null);
        btnSimpan.setEnabled(true);
        btnTambah.setEnabled(false);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        txtnik.setEnabled(true);
        txtnik.requestFocus();
    }
    
    private void tableToForm(){
        txtnik.setText(tabelModel.getValueAt(tblPenduduk.getSelectedRow(),1)+"");
        txtnamapen.setText(tabelModel.getValueAt(tblPenduduk.getSelectedRow(),2)+"");
        txtjenis_kelamin.setText(tabelModel.getValueAt(tblPenduduk.getSelectedRow(),3)+"");
        txttempat_lahir.setText(tabelModel.getValueAt(tblPenduduk.getSelectedRow(),4)+"");
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)tabelModel.getValueAt(tblPenduduk.getSelectedRow(),5));
            dateChooser.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(DataPendudukForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtagama.setText(tabelModel.getValueAt(tblPenduduk.getSelectedRow(),6)+"");
        txtpendidikan.setText(tabelModel.getValueAt(tblPenduduk.getSelectedRow(),7)+"");
        txtjenis_pekerjaan.setText(tabelModel.getValueAt(tblPenduduk.getSelectedRow(),8)+"");
        txtalamat.setText(tabelModel.getValueAt(tblPenduduk.getSelectedRow(),9)+"");
        cbxJenisPenduduk.setSelectedItem(tabelModel.getValueAt(tblPenduduk.getSelectedRow(),10)+"");
        txtnik.setEnabled(false);
        btnSimpan.setEnabled(false);
        btnTambah.setEnabled(true);
        btnUbah.setEnabled(true);
        btnHapus.setEnabled(true);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        txtnamapen = new javax.swing.JTextField();
        txtjenis_kelamin = new javax.swing.JTextField();
        txtagama = new javax.swing.JTextField();
        txtpendidikan = new javax.swing.JTextField();
        txtjenis_pekerjaan = new javax.swing.JTextField();
        txttempat_lahir = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPenduduk = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        cbxJenisPenduduk = new javax.swing.JComboBox<>();
        dateChooser = new com.toedter.calendar.JDateChooser();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DATA PENDUDUK");

        jLabel2.setText("NIK");

        jLabel3.setText("Nama");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Agama");

        jLabel6.setText("Pendidikan");

        jLabel7.setText("Jenis Pekerjaan");

        jLabel8.setText("Tempat Lahir");

        jLabel9.setText("Tanggal Lahir");

        txtnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnikActionPerformed(evt);
            }
        });

        txttempat_lahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttempat_lahirActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setText("Tutup");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jLabel10.setText("Jenis Penduduk");

        jLabel11.setText("Alamat");

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblPenduduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPenduduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPendudukMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPenduduk);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        cbxJenisPenduduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TETAP", "KONTRAK", "SEMENTARA", "LAINNYA" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnik, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(txtnamapen)
                                    .addComponent(txtjenis_kelamin)
                                    .addComponent(txtagama))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttempat_lahir)
                                    .addComponent(txtjenis_pekerjaan)
                                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtpendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(txtalamat)
                            .addComponent(cbxJenisPenduduk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(btnUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addGap(34, 34, 34)
                                .addComponent(btnKeluar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnamapen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtjenis_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtpendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtjenis_pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txttempat_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbxJenisPenduduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar)
                    .addComponent(btnTambah))
                .addGap(19, 19, 19))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttempat_lahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttempat_lahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttempat_lahirActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
        
        if(txtnik.getText().equals("")){
            JOptionPane.showMessageDialog(null, "NIK tidak boleh kosong");
            txtnik.requestFocus();
        }
        else if(txtnamapen.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong");
            txtnik.requestFocus();
        }else{
        String nik = txtnik.getText();
        String namapen = txtnamapen.getText();
        String jenis_kelamin = txtjenis_kelamin.getText();
        String tempat_lahir = txttempat_lahir.getText();
        String tanggal_lahir = Date_Format.format(dateChooser.getDate());
        String agama = txtagama.getText();
        String pendidikan = txtpendidikan.getText();
        String jenis_pekerjaan = txtjenis_pekerjaan.getText();
        String alamat = txtalamat.getText();
        String jenis_penduduk = (String) cbxJenisPenduduk.getSelectedItem();
        Penduduk p = new Penduduk(nik, namapen,jenis_kelamin,tempat_lahir,tanggal_lahir,agama,pendidikan,jenis_pekerjaan,alamat,jenis_penduduk);
        pController.setDml(p, OperasiCRUD.INSERT);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,"Apakah anda ingin menutup tab Data Penduduk?","Tutup Aplikasi",JOptionPane.YES_NO_OPTION);
        if(selectedOption == JOptionPane.YES_OPTION){
        dispose();
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnikActionPerformed

    private void tblPendudukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPendudukMouseClicked
        // TODO add your handling code here:
        tableToForm();
    }//GEN-LAST:event_tblPendudukMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
        
        String getId = tabelModel.getValueAt(tblPenduduk.getSelectedRow(),0).toString();
        int id = Integer.parseInt(getId);
        String nik = txtnik.getText();
        String namapen = txtnamapen.getText();
        String jenis_kelamin = txtjenis_kelamin.getText();
        String tempat_lahir = txttempat_lahir.getText();
        String tanggal_lahir = Date_Format.format(dateChooser.getDate());
        String agama = txtagama.getText();
        String pendidikan = txtpendidikan.getText();
        String jenis_pekerjaan = txtjenis_pekerjaan.getText();
        String alamat = txtalamat.getText();
        String jenis_penduduk = (String) cbxJenisPenduduk.getSelectedItem();
        Penduduk p = new Penduduk(id, nik, namapen,jenis_kelamin,tempat_lahir,tanggal_lahir,agama,pendidikan,jenis_pekerjaan,alamat,jenis_penduduk);
        pController.setDml(p, OperasiCRUD.UPDATE);
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String kode = txtnik.getText();
        Penduduk p = new Penduduk(kode);
        int hapus = JOptionPane.showConfirmDialog(null,"Apakah "
                + "Anda Yakin Ingin Menghapus Data", null, JOptionPane.YES_NO_OPTION);
        if(hapus == JOptionPane.YES_OPTION){
            pController.setDml(p,OperasiCRUD.DELETE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnTambahActionPerformed
    
    public void update(Observable o, Object arg){
        if(o == pController){
            Penduduk p = (Penduduk)arg;
            if(pController.getCrudState()== OperasiCRUD.INSERT){
                JOptionPane.showMessageDialog(this,"Data Berhasil di Simpan");
            }else if(pController.getCrudState()== OperasiCRUD.UPDATE){
                JOptionPane.showMessageDialog(this,"Data Berhasil di Update");
                btnSimpan.setEnabled(true);
                txtnik.setEnabled(true);
            }else if(pController.getCrudState()== OperasiCRUD.DELETE){
                JOptionPane.showMessageDialog(this,"Data Berhasil di Hapus");
                btnSimpan.setEnabled(true);
                txtnik.setEnabled(true);
        }
            setTabelPenduduk(pController.getAllPenduduk());
            resetForm();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPendudukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPendudukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPendudukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPendudukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPendudukForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbxJenisPenduduk;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblPenduduk;
    private javax.swing.JTextField txtagama;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtjenis_kelamin;
    private javax.swing.JTextField txtjenis_pekerjaan;
    private javax.swing.JTextField txtnamapen;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtpendidikan;
    private javax.swing.JTextField txttempat_lahir;
    // End of variables declaration//GEN-END:variables
}
