/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controllers.PendudukController;
import controllers.IuranController;
import java.awt.Image;
import java.util.ArrayList;
import models.IuranPenduduk;
import models.OperasiCRUD;
import models.Penduduk;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author fikry
 */
public class IuranForm extends javax.swing.JInternalFrame implements Observer {
    private IuranController iController = new IuranController();
    private PendudukController  pController = new PendudukController();
    DefaultTableModel tabelModel;

    /**
     * Creates new form IuranPendudukForm
     */
    public IuranForm() {
        initComponents();
        resetForm();
        iController.addObserver(this);
        setPenduduk(pController.getAllPenduduk());
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTabelIuran(iController.getAllIuran());
    }
    private void setPenduduk(List<Penduduk> pens){
        if(pens == null){
            JOptionPane.showMessageDialog(this, "Data Penduduk tidak Ada"
                        + "Diload","Gagal Koneksi", JOptionPane.ERROR_MESSAGE);
        }else{
            cbxPenduduk.setModel(new DefaultComboBoxModel(pens.toArray()));
            Object x = pens.toArray();
        }
    }
    
    private void resetForm(){
        txttagihan.setText(null);
        btnTambah.setEnabled(false);
        btnSimpan.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
    }
    
    private void tableToForm(){
        int rowIndex = tblIuran.getSelectedRow();
        cbxPenduduk.setSelectedIndex(rowIndex);
        txttagihan.setText(tabelModel.getValueAt(tblIuran.getSelectedRow(),2)+"");
        btnSimpan.setEnabled(false);
        btnTambah.setEnabled(true);
        btnUbah.setEnabled(true);
        btnHapus.setEnabled(true);
    }
    
    private void setTabelIuran(List<IuranPenduduk>daftarIuran){
        if(daftarIuran == null){
            JOptionPane.showMessageDialog(this, "Data Iuran tidak Ada"
                        + "Diload","Gagal Koneksi", JOptionPane.ERROR_MESSAGE);
        }else{
            tabelModel = new DefaultTableModel();
            tabelModel.setColumnIdentifiers(new String[]{
            "Kode Tagihan", "NIK", "Jumlah Tagihan"
        });
            for(IuranPenduduk i : daftarIuran){
                Object[] o = new Object[4];
                o[0] = i.getkode_t();
                o[1] = i.getPenduduk();
                o[2] = i.gettagihan();
                tabelModel.addRow(o);
            }
            tblIuran.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
            tblIuran.setModel(tabelModel);
        }
    }
    
    public void update(Observable o, Object arg){
        if (o == iController){
            IuranPenduduk i = (IuranPenduduk)arg;
            if(iController.getCrudState()== OperasiCRUD.INSERT){
                JOptionPane.showMessageDialog(this, "Data Berhasil Di simpan");
            } else if(iController.getCrudState()== OperasiCRUD.UPDATE){
                JOptionPane.showMessageDialog(this,"Data Berhasil di Update");
            } else if(iController.getCrudState()== OperasiCRUD.DELETE){
                JOptionPane.showMessageDialog(this,"Data Berhasil di Hapus");
            }
            setTabelIuran(iController.getAllIuran());
            resetForm();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIuran = new javax.swing.JTable();
        cbxPenduduk = new javax.swing.JComboBox();
        btnUbah = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        txttagihan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Jumlah Tagihan");

        jLabel4.setText("NIK");

        jLabel1.setText("IURAN PENDUDUK");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblIuran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblIuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIuranMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblIuran);

        cbxPenduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPendudukActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnKeluar.setText("Tutup");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(1, 1, 1))
                                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbxPenduduk, 0, 202, Short.MAX_VALUE)
                                            .addComponent(txttagihan))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPenduduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnTambah)
                    .addComponent(btnKeluar))
                .addGap(35, 35, 35))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean check() {
        ArrayList<String> numdata = new ArrayList<String>();

        for(int count = 0; count < tabelModel.getRowCount(); count++){
            numdata.add(tabelModel.getValueAt(count, 1).toString());
        }
        Penduduk pen = (Penduduk)cbxPenduduk.getSelectedItem();
        String x = pen + "";
        for (int i = 0; i < numdata.size(); i++) {
            if (numdata.get(i).equals(x)) {
                return true;
            }
        }
        
        return false;
    }
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Penduduk pen = (Penduduk)cbxPenduduk.getSelectedItem();
        String strTagihan = txttagihan.getText();
        if(txttagihan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Jumlah tagihan tidak boleh kosong");
            txttagihan.requestFocus();
        } else if (check()) {
            JOptionPane.showMessageDialog(null, "Data sudah ada, dengan nik: " + pen);  
        } else if (StringUtils.isNumeric(strTagihan)) {
            int t = Integer.parseInt(strTagihan);
            int x  = 0;
            IuranPenduduk i = new IuranPenduduk(x, t, pen);
            iController.setDml(i, OperasiCRUD.INSERT);
        } else {
            JOptionPane.showMessageDialog(null, "Input jumlah tagihan harus bilangan integer.");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
//        Penduduk pen = (Penduduk)cbxPenduduk.getSelectedItem();
        int kode = Integer.parseInt(tabelModel.getValueAt(tblIuran.getSelectedRow(),0).toString());
        IuranPenduduk i = new IuranPenduduk(kode);
        int hapus = JOptionPane.showConfirmDialog(null,"Apakah "
                + "Anda Yakin Ingin Menghapus Data", null, JOptionPane.YES_NO_OPTION);
        if(hapus == JOptionPane.YES_OPTION){
            iController.setDml(i,OperasiCRUD.DELETE);
        }
        resetForm();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblIuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIuranMouseClicked
        // TODO add your handling code here:
        tableToForm();
    }//GEN-LAST:event_tblIuranMouseClicked

    private void cbxPendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPendudukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPendudukActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        Penduduk pen = (Penduduk)cbxPenduduk.getSelectedItem();
        int kode_t = Integer.parseInt(tabelModel.getValueAt(tblIuran.getSelectedRow(),0).toString());
        String strTagihan = txttagihan.getText();
        if(txttagihan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Jumlah tagihan tidak boleh kosong");
            txttagihan.requestFocus();
        } else if (StringUtils.isNumeric(strTagihan)) {
            int t = Integer.parseInt(strTagihan);
            IuranPenduduk i = new IuranPenduduk(kode_t, t, pen);
            iController.setDml(i, OperasiCRUD.UPDATE);
            resetForm();
        } else {
            JOptionPane.showMessageDialog(null, "Input jumlah tagihan harus bilangan integer.");
        }
        
        
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IuranForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IuranForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IuranForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IuranForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IuranForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox cbxPenduduk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblIuran;
    private javax.swing.JTextField txttagihan;
    // End of variables declaration//GEN-END:variables

    private void setIconImage(Image image) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
