/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JFrame;

/**
 *
 * @author fikry
 */
public class MenuAplikasi extends javax.swing.JFrame {

    /**
     * Creates new form MenuAplikasi
     */
    public MenuAplikasi() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        Input = new javax.swing.JMenu();
        DataPendudukItem = new javax.swing.JMenuItem();
        DataStatus = new javax.swing.JMenuItem();
        DataIuran = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        laporanMenu = new javax.swing.JMenu();
        LaporanPendudukMenuItem = new javax.swing.JMenuItem();
        LaporanStatusMenu = new javax.swing.JMenuItem();
        iuranMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Input.setMnemonic('f');
        Input.setText("Input");
        Input.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        DataPendudukItem.setMnemonic('o');
        DataPendudukItem.setText("Data Penduduk");
        DataPendudukItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPendudukItemActionPerformed(evt);
            }
        });
        Input.add(DataPendudukItem);

        DataStatus.setText("Status Penduduk");
        DataStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataStatusActionPerformed(evt);
            }
        });
        Input.add(DataStatus);

        DataIuran.setText("Iuran Penduduk");
        DataIuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataIuranActionPerformed(evt);
            }
        });
        Input.add(DataIuran);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        Input.add(exitMenuItem);

        menuBar.add(Input);

        laporanMenu.setText("Cetak");
        laporanMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        LaporanPendudukMenuItem.setText("Laporan Data Penduduk");
        LaporanPendudukMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPendudukMenuItemActionPerformed(evt);
            }
        });
        laporanMenu.add(LaporanPendudukMenuItem);

        LaporanStatusMenu.setText("Laporan Status Penduduk");
        LaporanStatusMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanStatusMenuActionPerformed(evt);
            }
        });
        laporanMenu.add(LaporanStatusMenu);

        iuranMenu.setText("Laporan Iuran Penduduk");
        iuranMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iuranMenuActionPerformed(evt);
            }
        });
        laporanMenu.add(iuranMenu);

        menuBar.add(laporanMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void DataPendudukItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPendudukItemActionPerformed
        // TODO add your handling code here:
        DataPendudukForm dpf = new DataPendudukForm();
        desktopPane.add(dpf);
        dpf.setVisible(true);
    }//GEN-LAST:event_DataPendudukItemActionPerformed

    private void DataStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataStatusActionPerformed
        // TODO add your handling code here:
        StatusPendudukForm spf = new StatusPendudukForm();
        desktopPane.add(spf);
        spf.setVisible(true);
    }//GEN-LAST:event_DataStatusActionPerformed

    private void DataIuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataIuranActionPerformed
        // TODO add your handling code here:
        IuranForm ipf = new IuranForm();
        desktopPane.add(ipf);
        ipf.setVisible(true);
    }//GEN-LAST:event_DataIuranActionPerformed

    private void LaporanPendudukMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPendudukMenuItemActionPerformed
        // TODO add your handling code here:
        LaporanPendudukForm lf = new LaporanPendudukForm();
        desktopPane.add(lf);
        lf.setVisible(true);
    }//GEN-LAST:event_LaporanPendudukMenuItemActionPerformed

    private void LaporanStatusMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanStatusMenuActionPerformed
        // TODO add your handling code here:
        LaporanStatusPendudukForm lf = new LaporanStatusPendudukForm();
        desktopPane.add(lf);
        lf.setVisible(true);
    }//GEN-LAST:event_LaporanStatusMenuActionPerformed

    private void iuranMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iuranMenuActionPerformed
        // TODO add your handling code here:
        LaporanIuranForm lf = new LaporanIuranForm();
        desktopPane.add(lf);
        lf.setVisible(true);
    }//GEN-LAST:event_iuranMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAplikasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DataIuran;
    private javax.swing.JMenuItem DataPendudukItem;
    private javax.swing.JMenuItem DataStatus;
    private javax.swing.JMenu Input;
    private javax.swing.JMenuItem LaporanPendudukMenuItem;
    private javax.swing.JMenuItem LaporanStatusMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem iuranMenu;
    private javax.swing.JMenu laporanMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
